{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uigraph.secretName" . }}
  labels:
    {{- include "uigraph.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.keys.uigraphSecretKey }}: {{ .Values.secrets.values.uigraphSecretKey | quote }}
  {{ .Values.secrets.keys.storageAccessKey }}: {{ .Values.secrets.values.storageAccessKey | quote }}
  {{ .Values.secrets.keys.storageSecretKey }}: {{ .Values.secrets.values.storageSecretKey | quote }}
  {{ .Values.secrets.keys.postgresPassword }}: {{ .Values.secrets.values.postgresPassword | quote }}
  {{ .Values.secrets.keys.adminPassword }}: {{ .Values.secrets.values.adminPassword | quote }}
  {{ .Values.secrets.keys.figmaClientSecret }}: {{ .Values.secrets.values.figmaClientSecret | quote }}
  {{ .Values.secrets.keys.redisAuthToken }}: {{ .Values.secrets.values.redisAuthToken | quote }}
{{- end -}}
